### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by zhuhm1996** [AtomEcho/AtomGPT#11]
您好，我想使用AtomEchoAI/AtomGPT_14k预训练模型：
我的代码如下：
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model = AutoModelForCausalLM.from_pretrained('/home/sds/zhangkai/CfBigModel/AtomGPT_14k/',device_map='auto',load_in_8bit=True,torch_dtype=torch.float16)
model =model.eval()
tokenizer = AutoTokenizer.from_pretrained('/home/sds/zhangkai/CfBigModel/AtomGPT_14k/',trust_remote_code=True)
input_ids = tokenizer(['<s>Human: 介绍一下北京\n</s><s>Assistant: '], return_tensors="pt",add_special_tokens=False).input_ids.to('cuda')        
generate_input = {
    "input_ids":input_ids,
    "max_new_tokens":512,
    "do_sample":True,
    "top_k":50,
    "top_p":0.95,
    "temperature":0.3,
    "repetition_penalty":1.3,
    "eos_token_id":tokenizer.eos_token_id,
    "bos_token_id":tokenizer.bos_token_id,
    "pad_token_id":tokenizer.pad_token_id
}
generate_ids  = model.generate(**generate_input)
text = tokenizer.decode(generate_ids[0])
print(text)

报错信息如下：
Loading checkpoint shards:  86%|███████████████████████████████████▏     | 12/14 [00:18<00:03,  1.52s/it]
Traceback (most recent call last):
  File "/gpfs/home/sds/zhangkai/CfBigModel/AtomGPT/infer.py", line 4, in <module>
    model = AutoModelForCausalLM.from_pretrained('/home/sds/zhangkai/CfBigModel/AtomGPT_14k/',device_map='auto',trust_remote_code=True,load_in_8bit=True,torch_dtype=torch.float16)
  File "/home/sds/zhangkai/.conda/envs/LoraGLM/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/home/sds/zhangkai/.conda/envs/LoraGLM/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2656, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/sds/zhangkai/.conda/envs/LoraGLM/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2979, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/sds/zhangkai/.conda/envs/LoraGLM/lib/python3.10/site-packages/transformers/modeling_utils.py", line 673, in _load_state_dict_into_meta_model
    set_module_8bit_tensor_to_device(model, param_name, param_device, value=param)
  File "/home/sds/zhangkai/.conda/envs/LoraGLM/lib/python3.10/site-packages/transformers/utils/bitsandbytes.py", line 62, in set_module_8bit_tensor_to_device
    new_value = value.to("cpu")
NotImplementedError: Cannot copy out of meta tensor; no data!

请问，是什么原因？能帮我解决一下吗？谢谢！

**Comment by ZHangZHengEric** [comment]
感谢提出问题。我们检查了一遍，应该是这个hub上的模型上传不完整。我们再重新上传一次，深感抱歉

**Comment by zhuhm1996** [comment]
非常感谢您的回复！

**Comment by ZHangZHengEric** [comment]
经过我们测试，现在 AtomEchoAI/AtomGPT_14k 可以拉取了，感谢您指出问题。
